### ISSUE TITLE
Loot Table Issue

### ISSUE THREAD

**Issue by C0D6WasTaken** [ApolloDatapacks/rebalanced-loot#1]
Maps from shipwrecks seem to lose all of their NBT data thus making them useless. What I mean by that is that they revert back to a normal map.
I believe you have to replace `minecraft:map` with `minecraft:filled_map` in `data\minecraft\loot_tables\chests\shipwreck_map.json`

Also, would this be compatible with [Not Just Biomes](https://github.com/Apollounknowndev/not-just-biomes)?

**Comment by Apollounknowndev** [comment]
Treasure maps are intentionally removed from shipwrecks, due to them being a frequent source of crashing. The crashing isn't something I can fix, as it is a [vanilla issue](https://bugs.mojang.com/browse/MC-249136).
This pack is compatible with Not Just Biomes, yes.

**Comment by C0D6WasTaken** [comment]
Thanks! I wasn't aware of this bug and it's great to hear that it's compatible. Hopefully it gets fixed soon. Do you have any idea how this mechanic can be replaced until it gets fixed? Like treasure chests spawning with a glass block above them to mark their location. This way treasure chests can still be found at least.
